INFO: Log file created: D:\2025\Projects\Presence\Presence0.1\Uploader\Logs\20250307_020139.log


INFO: Channel provided from command line: RedNBlack
INFO: Earliest folder found: D:\2025\Projects\Presence\Presence0.1\Channels\RedNBlack\Clips\7_20250306_020137

INFO: YouTube AutoUpload for channel: 'RedNBlack', folder: 'D:\2025\Projects\Presence\Presence0.1\Channels\RedNBlack\Clips\7_20250306_020137'
ERROR: 'AutoUploadYouTube.py' failed with exit code 1
INFO: Video file: D:\2025\Projects\Presence\Presence0.1\Channels\RedNBlack\Clips\7_20250306_020137\7_20250306_020137.mp4 (Timestamp: 20250306_020137)
Traceback (most recent call last):
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 261, in <module>
    main()
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 252, in main
    bot = start_browser()
          ^^^^^^^^^^^^^^^
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 61, in start_browser
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 135.0.7049.3 with binary path C:\Program Files\Google\Chrome Beta\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00007FF6A10EB405+3109445]
	(No symbol) [0x00007FF6A0D6B190]
	(No symbol) [0x00007FF6A0C08FDA]
	(No symbol) [0x00007FF6A0C4CE2B]
	(No symbol) [0x00007FF6A0C4BE6B]
	(No symbol) [0x00007FF6A0C46306]
	(No symbol) [0x00007FF6A0C41596]
	(No symbol) [0x00007FF6A0C9545B]
	(No symbol) [0x00007FF6A0C94A30]
	(No symbol) [0x00007FF6A0C87013]
	(No symbol) [0x00007FF6A0C4FF5E]
	(No symbol) [0x00007FF6A0C511E3]
	GetHandleVerifier [0x00007FF6A114B41D+3502685]
	GetHandleVerifier [0x00007FF6A1166993+3614675]
	GetHandleVerifier [0x00007FF6A115BD23+3570531]
	GetHandleVerifier [0x00007FF6A0EBECBA+830202]
	(No symbol) [0x00007FF6A0D7643F]
	(No symbol) [0x00007FF6A0D72294]
	(No symbol) [0x00007FF6A0D72436]
	(No symbol) [0x00007FF6A0D61E89]
	BaseThreadInitThunk [0x00007FFC087B259D+29]
	RtlUserThreadStart [0x00007FFC09BAAF38+40]


