INFO: Log file created: D:\2025\Projects\Presence\Presence0.1\Uploader\Logs\20250311_152737.log


INFO: Channel provided from command line: The Science Of Getting Rich
INFO: Earliest folder found: D:\2025\Projects\Presence\Presence0.1\Channels\The Science Of Getting Rich\Clips\_Success_in_Small-Scale_Farming_

INFO: YouTube AutoUpload for channel: 'The Science Of Getting Rich', folder: 'D:\2025\Projects\Presence\Presence0.1\Channels\The Science Of Getting Rich\Clips\_Success_in_Small-Scale_Farming_'
ERROR: 'AutoUploadYouTube.py' failed with exit code 1
INFO: Video file: D:\2025\Projects\Presence\Presence0.1\Channels\The Science Of Getting Rich\Clips\_Success_in_Small-Scale_Farming_\_Success_in_Small-Scale_Farming_.mp4 (Timestamp: 20250304_205046)
Traceback (most recent call last):
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 261, in <module>
    main()
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 252, in main
    bot = start_browser()
          ^^^^^^^^^^^^^^^
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 61, in start_browser
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 135.0.7049.3 with binary path C:\Program Files\Google\Chrome Beta\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00007FF71C82B405+3109445]
	(No symbol) [0x00007FF71C4AB190]
	(No symbol) [0x00007FF71C348FDA]
	(No symbol) [0x00007FF71C38CE2B]
	(No symbol) [0x00007FF71C38BE6B]
	(No symbol) [0x00007FF71C386306]
	(No symbol) [0x00007FF71C381596]
	(No symbol) [0x00007FF71C3D545B]
	(No symbol) [0x00007FF71C3D4A30]
	(No symbol) [0x00007FF71C3C7013]
	(No symbol) [0x00007FF71C38FF5E]
	(No symbol) [0x00007FF71C3911E3]
	GetHandleVerifier [0x00007FF71C88B41D+3502685]
	GetHandleVerifier [0x00007FF71C8A6993+3614675]
	GetHandleVerifier [0x00007FF71C89BD23+3570531]
	GetHandleVerifier [0x00007FF71C5FECBA+830202]
	(No symbol) [0x00007FF71C4B643F]
	(No symbol) [0x00007FF71C4B2294]
	(No symbol) [0x00007FF71C4B2436]
	(No symbol) [0x00007FF71C4A1E89]
	BaseThreadInitThunk [0x00007FF887E9E8D7+23]
	RtlUserThreadStart [0x00007FF88913BF2C+44]


